[package]
name = "zgen"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.84"
prettyplease = "0.2.29"
zngur = { path = "../zngur" }
